# Generated by Django 4.2.4 on 2023-08-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=45, null=True)),
                ('price', models.IntegerField(null=True)),
                ('dealer', models.CharField(max_length=45, null=True)),
                ('dealer_contact', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('acquisition_brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mart.acquisition')),
                ('time', models.DateTimeField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('comments_optional', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('acquisition_brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mart.acquisition')),
                ('remainder', models.IntegerField(null=True)),
                ('comments_optional', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
