# Generated by Django 4.2.4 on 2023-08-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
