# Generated by Django 4.2.4 on 2023-09-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0004_acquisition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='acquisition_brand',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
