# Generated by Django 4.2.4 on 2023-09-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0005_remove_stock_acquisition_brand_delete_sales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_categories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_no', models.IntegerField()),
                ('job_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mart.job_categories')),
            ],
        ),
    ]
