# Generated by Django 4.2.4 on 2023-09-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0006_job_categories_shifts_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='period',
            field=models.DateTimeField(),
        ),
    ]
