# Generated by Django 4.2.4 on 2023-09-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0007_alter_shifts_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='period',
            field=models.TimeField(),
        ),
    ]
