# Generated by Django 4.2.4 on 2023-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0008_alter_shifts_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('supp_id', models.AutoField(primary_key=True, serialize=False)),
                ('supp_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cell_one', models.CharField(max_length=20)),
                ('cell_two', models.CharField(max_length=20)),
            ],
        ),
    ]
