# Generated by Django 4.2.4 on 2023-09-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0009_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='dealer_contact',
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mart.suppliers'),
        ),
    ]
