# Generated by Django 4.2.4 on 2023-09-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0012_acquisition_distr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='distr',
        ),
    ]
