# Generated by Django 4.2.4 on 2023-09-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0015_remove_acquisition_distr'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='distr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mart.suppliers'),
        ),
    ]
