# Generated by Django 4.2.4 on 2023-09-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0016_acquisition_distr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='dealer_contact',
        ),
    ]
