# Generated by Django 4.2.4 on 2023-09-22 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0017_remove_acquisition_dealer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_in_shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_status', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=100)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mart.staff')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mart.shifts')),
            ],
        ),
    ]
