# Generated by Django 4.2.4 on 2023-09-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0019_alter_shifts_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_in_shift',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
